version: '2'
networks:
    couchbase:
        driver: overlay
services:
    jhipster-couchbase-master:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        networks:
            - couchbase
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - TYPE=MASTER
    jhipster-couchbase-master:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        networks:
            - couchbase
        environment:
            - TYPE=WORKER
            - COUCHBASE-MASTER=jhipster-couchbase-master.couchbase
            - AUTO_REBALANCE=false

