version: '2'
services:
    jhipster-couchbase:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
#        volumes:
#            - ~/volumes/jhipster/jhipster/couchbase/:/opt/couchbase/var
